### PR TITLE
Update to tox 4.0 and simplify tox.ini

### PR DESCRIPTION
**Pull request by aliciaaevans**
**Work in progress** getting an error locally, but I want to see how it goes on Azure.

Updating the deprecated "whitelist_externals" and making some simplifications.

### CODE REVIEW

**Comment by piehld** [comment]
Thanks @aliciaaevans for working on this! Are these the only fixes needed to address the build issues?

**Comment by aliciaaevans** [comment]
> Thanks @aliciaaevans for working on this! Are these the only fixes needed to address the build issues?

Yes. the only reason I haven't set this to Ready for review is the local errors I'm getting.

**Comment by piehld** [comment]
OK I see, yeah it would be good to figure out how to resolve those local issues before proceeding with the merge. Have you gotten any closer into figuring out what the issue might be on your machine?

**Comment by aliciaaevans** [comment]
@epeisach @piehld 

Turns out there were some changes with packaging in tox 4: https://tox.wiki/en/latest/faq.html#tox-4-packaging-changes

Changing `usedevelop = true` the new option `package = editable-legacy`, allowing it to still use `pip install -e` instead of editable wheels which seems to be what is failing. (If we keep `usedevelop`, it overrides this `package` option with the new `editable` behavior, so it has to be removed.)

Any concerns about this approach?

**Review by piehld — APPROVED** [review]
Thank you researching and addressing this, @aliciaaevans! These fixes look good to me.

**Pull request merged**
